DROP TABLE user_roles IF EXISTS;
drop table VOTING_PROCESS if exists;
drop table voting_variants if exists ;
DROP TABLE users IF EXISTS;
drop table lunches if exists;
drop table VOTINGS if exists ;


DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ
  AS INTEGER
  START WITH 100000;

CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  email            VARCHAR(255)            NOT NULL,
  password         VARCHAR(255)            NOT NULL,
  enabled          BOOLEAN DEFAULT TRUE    NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx
  ON USERS (email);

CREATE TABLE user_roles
(
  user_id INTEGER NOT NULL,
  role    VARCHAR(255),

  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);

CREATE TABLE lunches
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  menu             VARCHAR(255)            NOT NULL
);

create table VOTINGS
(
  id              INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  voting_date     date,
  result          INTEGER,

  foreign key (result) references lunches (id)
);

create table voting_variants
(
  voting_id       INTEGER                 not null,
  lunch_id        INTEGER                 not null,

  constraint voting_variant unique (voting_id, lunch_id),
  foreign key (voting_id) references VOTINGS (id) on DELETE cascade,
  foreign key (lunch_id) references lunches (id)
);

create table voting_process
(
  voting_id     integer                   not null ,
  user_id       integer                   not null ,
  lunch_id      integer,

  constraint users_variant unique (voting_id, user_id),
  foreign key (voting_id) references VOTINGS (id),
  foreign key (user_id) references users (id),
  foreign key (lunch_id) references lunches (id)
)

/*CREATE TABLE meals
(
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  date_time   TIMESTAMP    NOT NULL,
  description VARCHAR(255) NOT NULL,
  calories    INT          NOT NULL,
  user_id     INTEGER      NOT NULL,
  FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX meals_unique_user_datetime_idx
  ON meals (user_id, date_time)*/